Rc v0.3.2
rstoneback/pysatCDF pull request #37
Opened 2022-04-27 23:55 UTC by rstoneback

Release Candidate for v0.3.2.

 - Includes fixes to improve building with modern systems
 - Compatible with pysat v3.0+
 - Adds template documents for pulls, community documents, testing via GitHub Actions.
 - Same CDF library version as last release.

2022-04-28 00:00 UTC, rstoneback commented on setup.py
> +    extra_f77_compile_args=['--std=legacy'],
This was a key input to get things going again.

2022-04-29 16:19 UTC, rstoneback commented
@gregstarr @asreimer Thanks for contributing to pysatCDF! Apologies it has taken so long to get this release out. I've updated the zenodo.json with my best attempt at correct author information. I'd appreciate it if you could review the info.

2022-04-30 22:18 UTC, gregstarr commented
> @gregstarr @asreimer Thanks for contributing to pysatCDF! Apologies it has taken so long to get this release out. I've updated the zenodo.json with my best attempt at correct author information. I'd appreciate it if you could review the info.

Looks good to me, thanks!

2022-05-03 15:06 UTC, jklenzing requested changes
It's looking good.  Some of the docstrings are missing, but we could bump that to the next version.  Running flake8 locally (with the extra docstring checks), I see 53 issues.  Most can be pushed off until the doc update, I've flagged some of the more critical ones.

/pysatCDF/_cdf.py:11:6: H304: No relative imports. 'from . import fortran_cdf' is a relative import

2022-05-03 15:09 UTC, jklenzing commented on setup.py
>  from numpy.distutils.command.build import build
can't flag the location, but referring to `numpy.distutils.core`

2022-05-03 18:34 UTC, jklenzing commented
Running unit tests for https://github.com/pysat/pysatNASA/pull/102 with this branch, I get the following error when trying to load any cdf instrument:
```
>       meta = pysat.Meta(pandas.DataFrame.from_dict(self.meta, orient='index'),
                          units_label=units_label, name_label=name_label,
                          fill_label=fill_label, plot_label=plot_label,
                          min_label=min_label, max_label=max_label,
                          notes_label=notes_label, desc_label=desc_label,
                          axis_label=axis_label)
E       TypeError: __init__() got an unexpected keyword argument 'units_label'
```
it stems from the `to_pysat` function.

2022-05-04 19:43 UTC, jklenzing commented on CONTRIBUTING.md
> +3. Clone your fork locally:
```suggestion
2. Clone your fork locally:
```

2022-05-10 15:02 UTC, jklenzing commented on CONTRIBUTING.md
> +^^^^^^^^^^^^^^^^^^^^^^^^
This isn't formatting correctly for some reason.

2022-05-10 16:04 UTC, aburrell commented on pysatCDF/_cdf.py
>          names : list_like
```suggestion
        names : list-like
```

Here and elsewhere.

2022-05-10 16:04 UTC, aburrell commented on pysatCDF/_cdf.py
> +        """Process and attach data from fortran_cdf.get_multi_*"""
```suggestion
        """Process and attach data from various `fortran_cdf` 'get' functions."""
```

2022-05-10 16:04 UTC, aburrell commented on pysatCDF/_cdf.py
> +                # Raise first error.
```suggestion
                # Raise the first error.
```

2022-05-10 16:04 UTC, aburrell commented on setup.cfg
> +  __init__.py
```suggestion
```

2022-05-10 16:04 UTC, aburrell commented on setup.py
> +# Shared library name, needed for some systems (do not use on Mac OS X)
```suggestion

# Shared library name, needed for some systems (do not use on Mac OS X)
```

2022-05-10 16:04 UTC, aburrell commented on setup.py
> +        # Add shared library, if provided
```suggestion

        # Add shared library, if provided
```

2022-05-11 18:38 UTC, rstoneback commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Describe the bug**
Thanks for the note. I copied the templates from somewhere in our ecosystem. I don't remember from which package now though. Will update.

2022-05-11 20:06 UTC, rstoneback commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**Describe the bug**
pysatMadrigal and pysatSpaceWeather have 
```
# Description
A clear and concise description of what the bug is, including a description
of what you expected the outcome to be.

```

while the others, pysat, Models, Missions, Seasons, and CDAAC have the same here. I'll copy from Madrigal/SpaceWeather. Went a bit out of strict ** to # replacement, but the SpaceWeather/Madrigal versions are two whole years newer than the other packages.

2022-05-12 01:19 UTC, rstoneback commented
Thanks for the feedback!

2022-05-12 18:04 UTC, jklenzing approved these changes
Looks good!

2022-05-12 19:18 UTC, rstoneback commented
Thanks everyone!

2022-05-12 19:18 UTC, merged